### ISSUE TITLE
Change layout.

### ISSUE THREAD

**Issue by MinecraftXwinP** [MinecraftXwinP/diplomat#1]
outline.yaml will be setting file for diplomat.
```yaml
version: '1'
preprocessors:
- type: chinese
  options:
    - mode: t2s
      from: zh-TW
      to: zh-CN
- type: copy
  options:
    - from: en
    - to: fr
output:
  - selectors:
      - admin
      - manage
    template:
      type: js
      options:
        filename: "{{.Lang}}.control-panel.js"
```
selector select keys by prefix

Translations will put in regular yaml file, likes:
```yaml
admin:
  message:
    hello:
      zh-TW: '您好'
      en: 'Hello!'
```
to support nested key structure.

language will be determine by last segment

admin.message.hello."zh-TW"
admin.message.hello."en"
